# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lambda CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        env: 
          CI: true 
        run: npm ci

      - name: Zip the Lambda package
        run: zip -r --test function.zip . -x "*.git*" "node_modules/aws-sdk/*" "*node_modules*" 
        
        
      - name: Create .env.json for Lambda
        run: |
          echo '{
            "url": "${{ secrets.URL }}",
            "dbase": "${{ secrets.DBASE}}",
            "collections": "${{ secrets.COLLECTIONS}}
          }' >> .env

          echo env

          
      # - name: Run tests
      #   run: npm test
